# ┏━━━━━━━━━━━━━┓
# ┃ Font Config ┃
# ┗━━━━━━━━━━━━━┛

[font]
# Geist Mono
# size = 13.0
# normal = { family = "Geist Mono", style="Light" }
# bold = { family = "Geist Mono", style = "Bold" }
# italic = { family = "Geist Mono", style="Light" }
# bold_italic = { family = "Geist Mono", style = "Bold Italic" }

# Ubuntu
# size = 15.0
# normal = { family = "UbuntuMono Nerd Font", style="Regular" }
# bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
# italic = { family = "UbuntuMono Nerd Font", style="Italic" }
# bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }

# JetBrains Mono NL
# size = 13.0
# normal = { family = "JetBrains Mono NL", style="Regular" }
# bold = { family = "JetBrains Mono NL", style = "Bold" }
# italic = { family = "JetBrains Mono NL", style="Italic" }
# bold_italic = { family = "JetBrains Mono NL", style = "Bold Italic" }

# Monaspace Radon Var
# size = 13.5
# normal = { family = "Monaspace Radon Var", style="Regular" }
# bold = { family = "Monaspace Radon Var", style = "Bold" }
# italic = { family = "Monaspace Radon Var", style="Italic" }
# bold_italic = { family = "Monaspace Radon Var", style = "Medium Italic" }

# Input Mono
size = 12
normal = { family = "Input Mono", style="Light" }
bold = { family = "Input Mono", style = "Medium" }
italic = { family = "Input Mono", style="Italic" }
bold_italic = { family = "Input Mono", style = "Medium Italic" }
