[keyboard]
bindings = [
  # Command: search in designated folders
  { key = "P", mods = "Command", chars = "cd $(fd . -I --absolute-path --min-depth 0 --max-depth 4 -t d --exclude node_modules --exclude .git ~/cakeauth ~/sokratech ~/lms ~/tms ~/revlo ~/locker ~/learn ~/projects ~/work ~/personal ~/vleete ~/sandbox ~/oss ~/arisanin | fzf) && cl \r" },

  # Command: delete entire line
  { key = "Back", mods = "Command", chars = "\u0015" },

  # Movement: step 1 word forward
  { key = "Right", mods = "Alt", chars = "\u001bf" },

  # Movement: step 1 word backward
  { key = "Left", mods = "Alt", chars = "\u001bb" },

  # Movement: jump to the end of line
  { key = "Right", mods = "Command", chars = "\u001b[F" },

  # Movement: jump to the beginning of line
  { key = "Left", mods = "Command", chars = "\u001b[H" },

  # Neovim: cmd+enter
  { key = "Return", mods = "Command", chars = "<<<ORG_OPEN_AT_POINT>>>" },

  # Neovim: delete a word
  { key = "Back", mods = "Alt", chars = "\u0017" },

  # Tmux: new session
  { key = "T", mods = "Command", chars = "\u0002c" },

  # Tmux: rename window
  { key = "R", mods = "Command", chars = "\u0002," },

  # Tmux: close a session
  { key = "W", mods = "Command", chars = "\u0002&" },

  # Tmux: split window vertically
  { key = "D", mods = "Command", chars = "\u0002%" },

  # Tmux: split window horizontally
  { key = "D", mods = "Command|Shift", chars = "\u0002\"" },

  # Tmux: jump to tmux panes [1-9]
  { key = "Key1", mods = "Command", chars = "\u0002\u0031" },
  { key = "Key2", mods = "Command", chars = "\u0002\u0032" },
  { key = "Key3", mods = "Command", chars = "\u0002\u0033" },
  { key = "Key4", mods = "Command", chars = "\u0002\u0034" },
  { key = "Key5", mods = "Command", chars = "\u0002\u0035" },
  { key = "Key6", mods = "Command", chars = "\u0002\u0036" },
  { key = "Key7", mods = "Command", chars = "\u0002\u0037" },
  { key = "Key8", mods = "Command", chars = "\u0002\u0038" },
  { key = "Key9", mods = "Command", chars = "\u0002\u0039" },
]
